pipeline {
  agent { docker { image 'python:3.8' } }
  stages {
    stage('build') {
      steps {
        withEnv(["HOME=${env.WORKSPACE}"]) {
          sh 'python -m pip install --user -r sherlock_wrapper/requirements.txt'
        }
      }
    }
    stage('test') {
      steps {
        dir('tests') {
          sh 'python test_sherlock_wrapper.py'
        }
      }
    }
  }
}
