pipeline {
  agent { docker { image 'gpfrancis/sherlock-test:0.5' } }
  stages {
    stage('test') {
      steps {
        dir('tests') {
          sh 'python3 test_sherlock_wrapper.py'
        }
        dir('/opt/kafka_2.12-2.5.0') {
          sh 'id'
          sh 'sudo service mysql start'
          sh 'nohup bin/zookeeper-server-start.sh config/zookeeper.properties &'
          sh 'nohup bin/kafka-server-start.sh config/server.properties &'
        }
        dir('tests') {
          sh 'python3 integration_test_sherlock_wrapper.py'
        }
      }
      post {
        always {
          junit 'tests/test-reports/*.xml'
        }  
      }
    }
  }
}
