CREATE TABLE IF NOT EXISTS crossmatch_tns(
`ra` double,
`decl` double,
`tns_name` varchar(16),
`tns_prefix` varchar(16),
`disc_mag` float,
`disc_mag_filter` varchar(16),
`type` varchar(80),
`z` float,
`hostz` float DEFAULT NULL,
`host_name` varchar(80) DEFAULT NULL,
`ext_catalogs` varchar(80) DEFAULT NULL,
`disc_int_name` varchar(80),
`disc_date` datetime(6),
`lastmodified_date` datetime(6),
`sender` varchar(16),
`reporters` varchar(80),
`source_group` varchar(16),
`htm16` bigint(20),
`lasairmodified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
id int(10) unsigned NOT NULL AUTO_INCREMENT,
PRIMARY KEY (`id`),
KEY `idx_htm16` (`htm16`)
)
