USE ztf;
CREATE TABLE IF NOT EXISTS objects(
`objectId` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
`decmean` double,
`decstd` double,
`ramean` double,
`rastd` double,
`glatmean` double,
`glonmean` double,
`jdgmax` double,
`gmag` float,
`dmdt_g` float,
`dmdt_g_2` float,
`mag_g02` float,
`mag_g08` float,
`mag_g28` float,
`maggmax` float,
`maggmean` float,
`maggmin` float,
`jdrmax` double,
`mag_r02` float,
`mag_r08` float,
`mag_r28` float,
`rmag` float,
`dmdt_r` float,
`dmdt_r_2` float,
`magrmax` float,
`magrmean` float,
`magrmin` float,
`jdmax` double,
`jdmin` double,
`ncand` int,
`ncandgp` int,
`distpsnr1` float,
`sgscore1` float,
`sgmag1` float,
`srmag1` float,
`htm16` bigint(20),
`g_minus_r` float,
`jd_g_minus_r` double,
`ncandgp_7` int,
`ncandgp_14` int,
`ssnamenr` varchar(16),
PRIMARY KEY (`objectId`),
KEY `htmid16idx` (`htm16`),
KEY `idx_ncand` (`ncand`),
KEY `idx_ramean` (`ramean`),
KEY `idx_decmean` (`decmean`),
KEY `idx_jdmin` (`jdmin`),
KEY `idx_jdgmax` (`jdgmax`),
KEY `idx_jdrmax` (`jdrmax`),
KEY `idx_jdmax` (`jdmax`),
KEY `idx_htm16` (`htm16`),
KEY `idx_sgscore1` (`sgscore1`),
KEY `idx_distpsnr1` (`distpsnr1`),
KEY `idx_ncandgp` (`ncandgp`)
)