CREATE TABLE objects(
`objectId` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
`decmean` double,
`decstd` double,
`distpsnr1` float,
`glatmean` double,
`glonmean` double,
`jdmax` double,
`jdmin` double,
`latest_dc_mag_g` float,
`latest_dc_mag_g02` float,
`latest_dc_mag_g08` float,
`latest_dc_mag_g28` float,
`latest_dc_mag_r` float,
`latest_dc_mag_r02` float,
`latest_dc_mag_r08` float,
`latest_dc_mag_r28` float,
`latestgmag` float,
`latestrmag` float,
`maggmax` float,
`maggmean` float,
`maggmedian` float,
`maggmin` float,
`magrmax` float,
`magrmean` float,
`magrmedian` float,
`magrmin` float,
`ncand` int,
`ncandgp` int,
`ramean` double,
`rastd` double,
`sgmag1` float,
`sgscore1` float,
`srmag1` float,
`htm16` bigint(20),
PRIMARY KEY (`objectId`),
KEY `htmid16idx` (`htm16`),
KEY `idx_ncand` (`ncand`),
KEY `idx_ramean` (`ramean`),
KEY `idx_rastd` (`rastd`),
KEY `idx_decmean` (`decmean`),
KEY `idx_decstd` (`decstd`),
KEY `idx_maggmin` (`maggmin`),
KEY `idx_maggmax` (`maggmax`),
KEY `idx_maggmedian` (`maggmedian`),
KEY `idx_maggmean` (`maggmean`),
KEY `idx_magrmin` (`magrmin`),
KEY `idx_magrmax` (`magrmax`),
KEY `idx_magrmedian` (`magrmedian`),
KEY `idx_magrmean` (`magrmean`),
KEY `idx_latestgmag` (`latestgmag`),
KEY `idx_latestrmag` (`latestrmag`),
KEY `idx_jdmin` (`jdmin`),
KEY `idx_jdmax` (`jdmax`),
KEY `idx_glatmean` (`glatmean`),
KEY `idx_glonmean` (`glonmean`),
KEY `idx_htm16` (`htm16`),
KEY `idx_sgmag1` (`sgmag1`),
KEY `idx_srmag1` (`srmag1`),
KEY `idx_sgscore1` (`sgscore1`),
KEY `idx_distpsnr1` (`distpsnr1`),
KEY `idx_ncandgp` (`ncandgp`)
)
