CREATE TABLE `objects` (
  `primaryId` int(11) NOT NULL AUTO_INCREMENT,
  `objectId` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `stale` tinyint(4) DEFAULT '1',
  `ncand` int(11) NOT NULL DEFAULT '0',
  `ramean` double DEFAULT NULL,
  `rastd` double DEFAULT NULL,
  `decmean` double DEFAULT NULL,
  `decstd` double DEFAULT NULL,
  `maggmin` float DEFAULT NULL,
  `maggmax` float DEFAULT NULL,
  `maggmedian` float DEFAULT NULL,
  `maggmean` float DEFAULT NULL,
  `magrmin` float DEFAULT NULL,
  `magrmax` float DEFAULT NULL,
  `magrmedian` float DEFAULT NULL,
  `magrmean` float DEFAULT NULL,
  `latestgmag` float DEFAULT NULL,
  `latestrmag` float DEFAULT NULL,
  `jdmin` double DEFAULT NULL,
  `jdmax` double DEFAULT NULL,
  `sherlock_classification` varchar(10) DEFAULT NULL,
  `glatmean` double DEFAULT NULL,
  `glonmean` double DEFAULT NULL,
  `htm16` bigint(20) DEFAULT NULL,
  `latest_dc_mag_g` float DEFAULT NULL,
  `latest_dc_mag_r` float DEFAULT NULL,
  `latest_dc_mag_r02` float DEFAULT NULL,
  `latest_dc_mag_g02` float DEFAULT NULL,
  `latest_dc_mag_r08` float DEFAULT NULL,
  `latest_dc_mag_g08` float DEFAULT NULL,
  `latest_dc_mag_r28` float DEFAULT NULL,
  `latest_dc_mag_g28` float DEFAULT NULL,
  `sgmag1` float DEFAULT NULL,
  `srmag1` float DEFAULT NULL,
  `sgscore1` float DEFAULT NULL,
  `distpsnr1` float DEFAULT NULL,
  `ncandgp` int(11) DEFAULT '0',
  PRIMARY KEY (`primaryId`),
  UNIQUE KEY `objectId_UNIQUE` (`objectId`),
  KEY `htmid16idx` (`htm16`),
  KEY `idx_ncand` (`ncand`),
  KEY `idx_ramean` (`ramean`),
  KEY `idx_rastd` (`rastd`),
  KEY `idx_decmean` (`decmean`),
  KEY `idx_decstd` (`decstd`),
  KEY `idx_maggmin` (`maggmin`),
  KEY `idx_maggmax` (`maggmax`),
  KEY `idx_maggmedian` (`maggmedian`),
  KEY `idx_maggmean` (`maggmean`),
  KEY `idx_magrmin` (`magrmin`),
  KEY `idx_magrmax` (`magrmax`),
  KEY `idx_magrmedian` (`magrmedian`),
  KEY `idx_magrmean` (`magrmean`),
  KEY `idx_latestgmag` (`latestgmag`),
  KEY `idx_latestrmag` (`latestrmag`),
  KEY `idx_jdmin` (`jdmin`),
  KEY `idx_jdmax` (`jdmax`),
  KEY `idx_sherlock_classification` (`sherlock_classification`),
  KEY `idx_glatmean` (`glatmean`),
  KEY `idx_glonmean` (`glonmean`),
  KEY `idx_htm16` (`htm16`),
  KEY `idx_sgmag1` (`sgmag1`),
  KEY `idx_srmag1` (`srmag1`),
  KEY `idx_sgscore1` (`sgscore1`),
  KEY `idx_distpsnr1` (`distpsnr1`),
  KEY `idx_ncandgp` (`ncandgp`)
)
