CREATE DATABASE ztf;
USE ztf;
CREATE USER 'ztf'@'localhost' IDENTIFIED BY '123password';
CREATE USER 'ztf'@'%1' IDENTIFIED BY '123password';
GRANT ALL PRIVILEGES ON ztf.* TO 'ztf'@'localhost';
GRANT FILE ON *.* TO 'ztf'@'localhost';
CREATE USER 'readonly_ztf2'@'localhost' IDENTIFIED BY 'read123password';
CREATE USER 'readonly_ztf2'@'%' IDENTIFIED BY 'read123password';
GRANT SELECT ON ztf.* TO 'readonly_ztf2'@'%';
CREATE FUNCTION jdnow () RETURNS DOUBLE DETERMINISTIC RETURN (unix_timestamp(now())/86400 + 2440587.5);
GRANT EXECUTE ON FUNCTION ztf.jdnow TO 'readonly_ztf2'@'%';
