---
- hosts: dask
  gather_facts: no
  tasks:
    - name: python3-pip
      apt: 
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: install dask[bag]
      pip: 
          executable: pip3 
          name: dask[distributed]
      become: yes

    - name: install dask[distributed]
      pip: 
          executable: pip3 
          name: dask[distributed]
      become: yes

    - name: install jupyter
      pip: 
          executable: pip3 
          name: jupyter
      become: yes

    - name: install bokeh
      pip: 
          executable: pip3 
          name: bokeh
      become: yes

    - name: install cassandra client
      pip:
          executable: pip3
          name: cassandra-driver
      become: yes

    - name: Make sure the repo is up to date
      git:
          repo: https://github.com/lsst-uk/lasair-lsst.git
          dest: /home/ubuntu/lasair-lsst

#$ jupyter notebook password
#$ jupyter notebook --generate-config
#then edit ~/.jupyter/jupyter_notebook_config.py
#c.NotebookApp.ip = '*'
#c.NotebookApp.port = 8080
#c.NotebookApp.open_browser = False

