---
- hosts: filter_nodes
  gather_facts: no
  tasks:
    - name: install pip3
      apt: 
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: install numpy
      pip: 
          executable: pip3 
          name: numpy
      become: yes

    - name: install ephem
      pip: 
          executable: pip3 
          name: ephem
      become: yes

    - name: install confluent kafka
      pip: 
          executable: pip3 
          name: confluent-kafka
      become: yes

    - name: install mysql.connector
      pip: 
          executable: pip3 
          name: mysql-connector-python

    - name: install MOC
      pip: 
          executable: pip3 
          name: mocpy

    - name: install mysql
      apt: 
          name: mysql-server
          state: present
          update_cache: true
      become: yes

    - name: Start the MySQL service
      service:
          name: mysql
          state: started

    - name: permissions on mysql-files
      file:
          path: /var/lib/mysql-files
          mode: '777'
      become: yes

    - name: Creates directory
      file:
          path: /home/ubuntu/scratch
          state: directory

    - name: Make sure the repo is up to date
      git: 
          repo: https://github.com/lsst-uk/lasair-lsst.git
          dest: /home/ubuntu/lasair-lsst

# mysql -u ztf -p ztf < ../utility/mysql_setup.sql
# mysql -u ztf -p ztf < ../utility/schema/objects.sql
# mysql -u ztf -p ztf < ../utility/schema/sherlock_crossmatches.sql
