# first install mysql
# git clone https://github.com/genghisken/gkansible.git
# follow instructions in readme.md
# ansible-playbook install-mysql.yml
---
- hosts: filter_nodes
  gather_facts: no
  tasks:
    - name: install swig
      apt: 
          name: swig
          state: present
          update_cache: true
      become: yes

    - name: install python-dev
      apt: 
          name: python-dev
          state: present
          update_cache: true
      become: yes

    - name: install pip3
      apt: 
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: install gkhtm
      pip: 
          executable: pip3 
          name: gkhtm
      become: yes

    - name: install numpy
      pip: 
          executable: pip3 
          name: numpy
      become: yes

    - name: install ephem
      pip: 
          executable: pip3 
          name: ephem
      become: yes

    - name: install confluent kafka
      pip: 
          executable: pip3 
          name: confluent-kafka
      become: yes

    - name: install mysql.connector
      pip: 
          executable: pip3 
          name: mysql-connector-python

    - name: install MOC
      pip: 
          executable: pip3 
          name: mocpy

    - name: install mysql
      apt: 
          name: mysql-server
          state: present
          update_cache: true
      become: yes

    # Added by KWS for gkdbutils - not sure it's required.
    # KWS START
    - name: install mysql
      apt: 
          name: libmysqlclient-dev
          state: present
          update_cache: true
      become: yes

    - name: install MySQLdb
      pip: 
          executable: pip3 
          name: mysqlclient

    - name: install Cassandra client
      pip: 
          executable: pip3 
          name: cassandra-driver

    - name: install gkdbutils
      pip: 
          executable: pip3 
          name: gkdbutils

    # KWS END

    - name: Start the MySQL service
      service:
          name: mysql
          state: started

    - name: permissions on mysql-files
      file:
          path: /var/lib/mysql-files
          mode: '777'
      become: yes

    - name: Creates directory
      file:
          path: /home/ubuntu/scratch
          state: directory

    - name: Copy git credentials
      copy:
        src: /home/ubuntu/.git-credentials
        dest: /home/ubuntu/.git-credentials

    - name: Copy settings file
      copy:
        src: /home/ubuntu/lasair-lsst/filter/settings.py
        dest: /home/ubuntu/lasair-lsst/filter/settings.py

    - name: Creates directory for logs
      file:
        path: /home/ubuntu/logs
        state: directory

    - name: Make sure the repo is up to date
      git: 
          repo: https://github.com/lsst-uk/lasair-lsst.git
          dest: /home/ubuntu/lasair-lsst

    - name: run mysql setup
      shell:
          cmd: mysql --user=root --password=root123password < mysql_setup.sql
          chdir: /home/ubuntu/lasair-lsst/utility

    - name: create object table
      shell:
          cmd: mysql --user=ztf --password=123password < objects.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create sherlock_classifications table
      shell:
          cmd: mysql --user=ztf --password=123password < sherlock_classifications.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create area_hits table
      shell:
          cmd: mysql --user=ztf --password=123password < area_hits.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create watchlist_hits table
      shell:
          cmd: mysql --user=ztf --password=123password < watchlist_hits.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema
