# how to deploy the filter nodes
#
# (1) run ken's ansible to set up the mysql
# cd ~
# git clone https://github.com/genghisken/gkansible.git
# cd ~/gkansible/gkansible
# cp ansible_example.cfg ansible.cfg
# cp hosts_example.yml file hosts.yml and edit with IPs
# set mysql_root_password in roles/install-mysql/defaults/main.yml 
# ansible-playbook install-mysql.yml
#
# (2) run marks cephfs
# cd ~/lasair-lsst/ansible
# change hosts.yml to new cephfs_nodes
# ansible-playbook --inventory-file=hosts.yml mount_cephfs.yml
#
# (3) run roy's filter deploy
# change hosts.yml to new filter_nodes 
# ansible-playbook --inventory-file=hosts.yml filter.yml
# 
---
- hosts: filter_nodes
  gather_facts: no

  vars:
      settings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings')}}"
      ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: install swig
      apt: 
          name: swig
          state: present
          update_cache: true
      become: yes

    - name: install python3-dev
      apt: 
          name: python-dev
          state: present
          update_cache: true
      become: yes

    - name: install pip3
      apt: 
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: install postfix email
      apt:
          name: postfix
          state: present
          update_cache: true
      become: yes

    - name: install gkhtm
      pip: 
          executable: pip3 
          name: gkhtm
      become: yes

    - name: install gkutils
      pip: 
          executable: pip3 
          name: gkutils
      become: yes

    - name: install numpy
      pip: 
          executable: pip3 
          name: numpy
      become: yes

    - name: install ephem
      pip: 
          executable: pip3 
          name: ephem
      become: yes

    - name: install confluent kafka
      pip: 
          executable: pip3 
          name: confluent-kafka==1.5
      become: yes

    - name: install mysql.connector
      pip: 
          executable: pip3 
          name: mysql-connector-python

    - name: install MOC
      pip: 
          executable: pip3 
          name: mocpy

    - name: csvfiles directory
      file:
          path: /home/ubuntu/csvfiles/
          state: directory
          mode: '777'
      become: yes

    - name: modify apparmor so MySQL can write
      lineinfile:
        dest: /etc/apparmor.d/usr.sbin.mysqld
        line: /home/ubuntu/csvfiles/** rwk,
        insertbefore: "}"
        state: present
      become: yes

    - name: restart apparmor
      service:
        name: apparmor
        state: restarted
        enabled: yes
      become: true

    - name: Copy git credentials
      copy:
        src: /home/ubuntu/.git-credentials
        dest: /home/ubuntu/.git-credentials

    - name: Creates directory for logs
      file:
        path: /home/ubuntu/logs
        state: directory

    - name: Make sure the repo is up to date
      git: 
          repo: https://github.com/lsst-uk/lasair-lsst.git
          dest: /home/ubuntu/lasair-lsst

    - name: settings.py for filter module
      template:
        src:  /home/ubuntu/lasair-lsst/filter/settings.py.j2
        dest: /home/ubuntu/lasair-lsst/filter/settings.py 

    - name: run mysql setup
      shell:
          cmd: mysql --user=root --password=root123password < mysql_setup.sql
          chdir: /home/ubuntu/lasair-lsst/utility

    - name: create object table
      shell:
          cmd: mysql --user=ztf --password=123password < objects.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create sherlock_classifications table
      shell:
          cmd: mysql --user=ztf --password=123password < sherlock_classifications.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create crossmatch_tns table
      shell:
          cmd: mysql --user=ztf --password=123password < crossmatch_tns.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create area_hits table
      shell:
          cmd: mysql --user=ztf --password=123password < area_hits.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create watchlist_hits table
      shell:
          cmd: mysql --user=ztf --password=123password < watchlist_hits.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create annotations table
      shell:
          cmd: mysql --user=ztf --password=123password < annotations.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema
