# change hosts.yml to new filter_nodes and new cephfs_nodes
# cd ~
# git clone https://github.com/genghisken/gkansible.git
# cd ~/gkansible/gkansible
# cp ansible_example.cfg ansible.cfg
# cp hosts_example.yml file hosts.yml
# set mysql_root_password in roles/install-mysql/defaults/main.yml 
# edit hosts for correct IP
# ansible-playbook install-mysql.yml
#
# cd ~/lasair-lsst/ansible
# ansible-playbook --inventory-file=hosts.yml mount_cephfs.yml
#
# ansible-playbook --inventory-file=hosts.yml filter.yml
---
- hosts: filter_nodes
  gather_facts: no
  tasks:
    - name: install swig
      apt: 
          name: swig
          state: present
          update_cache: true
      become: yes

    - name: install python-dev
      apt: 
          name: python-dev
          state: present
          update_cache: true
      become: yes

    - name: install pip3
      apt: 
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: install gkhtm
      pip: 
          executable: pip3 
          name: gkhtm
      become: yes

    - name: install gkutils
      pip: 
          executable: pip3 
          name: gkutils
      become: yes

    - name: install numpy
      pip: 
          executable: pip3 
          name: numpy
      become: yes

    - name: install ephem
      pip: 
          executable: pip3 
          name: ephem
      become: yes

    - name: install confluent kafka
      pip: 
          executable: pip3 
          name: confluent-kafka
      become: yes

    - name: install mysql.connector
      pip: 
          executable: pip3 
          name: mysql-connector-python

    - name: install MOC
      pip: 
          executable: pip3 
          name: mocpy

    - name: install Cassandra client
      pip: 
          executable: pip3 
          name: cassandra-driver

    - name: permissions on mysql-files
      file:
          path: /data/mysql/mysqltmp
          mode: '777'
      become: yes

    - name: Copy git credentials
      copy:
        src: /home/ubuntu/.git-credentials
        dest: /home/ubuntu/.git-credentials

    - name: Creates directory for logs
      file:
        path: /home/ubuntu/logs
        state: directory

    - name: Make sure the repo is up to date
      git: 
          repo: https://github.com/lsst-uk/lasair-lsst.git
          dest: /home/ubuntu/lasair-lsst

    - name: Copy settings file
      copy:
        src: /home/ubuntu/lasair-lsst/filter/settings.py
        dest: /home/ubuntu/lasair-lsst/filter/settings.py

    - name: run mysql setup
      shell:
          cmd: mysql --user=root --password=root123password < mysql_setup.sql
          chdir: /home/ubuntu/lasair-lsst/utility

    - name: create object table
      shell:
          cmd: mysql --user=ztf --password=123password < objects.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create sherlock_classifications table
      shell:
          cmd: mysql --user=ztf --password=123password < sherlock_classifications.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create area_hits table
      shell:
          cmd: mysql --user=ztf --password=123password < area_hits.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema

    - name: create watchlist_hits table
      shell:
          cmd: mysql --user=ztf --password=123password < watchlist_hits.sql
          chdir: /home/ubuntu/lasair-lsst/utility/schema
