# change hosts.yml to new rdbms
# cd ~
# git clone https://github.com/genghisken/gkansible.git
# cd ~/gkansible/gkansible
# cp ansible_example.cfg ansible.cfg
# cp hosts_example.yml file hosts.yml
# set mysql_root_password in roles/install-mysql/defaults/main.yml
# edit hosts for correct IP
# ansible-playbook install-mysql.yml
#
# cd ~/lasair-lsst/ansible
# ansible-playbook --inventory-file=hosts.yml lasair-db.yml
---
- hosts: rdbms
  gather_facts: no
  tasks:
    - name: install pip3
      apt: 
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: permissions on mysql-files
      file:
          path: /var/lib/mysql-files
          mode: '777'
      become: yes

    - name: Creates directory
      file:
          path: /home/ubuntu/scratch
          state: directory

    - name: Copy git credentials
      copy:
        src: /home/ubuntu/.git-credentials
        dest: /home/ubuntu/.git-credentials

    - name: Make sure the repo is up to date
      git: 
          repo: https://github.com/lsst-uk/lasair-lsst.git
          dest: /home/ubuntu/lasair-lsst

    - name: Copy settings.py
      copy:
        src: /home/ubuntu/lasair-lsst/lasair-db/settings.py
        dest: /home/ubuntu/lasair-lsst/lasair-db/settings.py

    - name: Copy mysqlbackup.sh
      copy:
        src: /home/ubuntu/lasair-lsst/lasair-db/mysqlbackup.sh
        dest: /home/ubuntu/lasair-lsst/lasair-db/mysqlbackup.sh

    - name: Copy crossmatch_tns_dump.sh
      copy:
        src: /home/ubuntu/lasair-lsst/lasair-db/crossmatch_tns_dump.sh
        dest: /home/ubuntu/lasair-lsst/lasair-db/crossmatch_tns_dump.sh

        #    - name: run mysql setup
        #      shell:
        #          cmd: mysql --user=root --password=root123password < mysql_setup.sql
          #          chdir: /home/ubuntu/lasair-lsst/utility
          #
          #    - name: create object table
          #      shell:
              #          cmd: mysql --user=ztf --password=123password < objects.sql
              #          chdir: /home/ubuntu/lasair-lsst/utility/schema

        #    - name: create sherlock_classifications table
        #      shell:
        #          cmd: mysql --user=ztf --password=123password < sherlock_classifications.sql
        #          chdir: /home/ubuntu/lasair-lsst/utility/schema

        #    - name: create area_hits table
        #      shell:
        #          cmd: mysql --user=ztf --password=123password < area_hits.sql
        #          chdir: /home/ubuntu/lasair-lsst/utility/schema

        #    - name: create watchlist_hits table
        #      shell:
        #          cmd: mysql --user=ztf --password=123password < watchlist_hits.sql
        #          chdir: /home/ubuntu/lasair-lsst/utility/schema
