---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
          test: "{{ lookup('hashi_vault', 'secret=secret/lasair/test')}}"

  tasks:

    - name: "settings.py for filter module"
      template:
        src:  ../filter/settings.py.j2
        dest: ../filter/settings.py 

    - name: "settings.py for ingest module"
      template:
        src:  ../ingest/settings.py.j2
        dest: ../ingest/settings.py 

    - name: "settings.py for lasair-db module"
      template:
        src:  ../lasair-db/settings.py.j2
        dest: ../lasair-db/settings.py 

    - name: "settings.py for services/TNS module"
      template:
        src:  ../services/TNS/settings.py.j2
        dest: ../services/TNS/settings.py 

    - name: "settings.py for services/areas module"
      template:
        src:  ../services/areas/settings.py.j2
        dest: ../services/areas/settings.py 

    - name: "settings.py for services/watchlists module"
      template:
        src:  ../services/watchlists/settings.py.j2
        dest: ../services/watchlists/settings.py 

    - name: "settings.py for lasair-db/crossmatch_tns_dump"
      template:
        src:  ../lasair-db/crossmatch_tns_dump.sh.j2
        dest: ../lasair-db/crossmatch_tns_dump.sh

    - name: "settings.py for lasair-db/mysqlbackup"
      template:
        src:  ../lasair-db/mysqlbackup.sh.j2
        dest: ../lasair-db/mysqlbackup.sh
