#- hosts: ingest_nodes
- hosts: cephfs_nodes
  remote_user: ubuntu
  gather_facts: no
  become: yes

  tasks:
  - name: Create /etc/ceph directory
    file:
      path: /etc/ceph
      state: directory
      mode: '0755'

  - name: Create the /mnt/cephfs mount directory
    file:
      path: /mnt/cephfs
      state: directory
      mode: '0755'

  - name: add the fstab entry for mounting on boot
    lineinfile:
        path: /etc/fstab
        line: '192.41.108.11:6789:/ /mnt/cephfs ceph _netdev,noatime,name=admin,secretfile=/etc/ceph/ceph.client.admin.keyring 0 2'

  - name: copy the hosts file
    copy: src=/etc/hosts dest=/etc/hosts owner=root group=root mode=0644

  - name: copy the ceph.conf file
    copy: src=/etc/ceph/ceph.conf dest=/etc/ceph/ceph.conf owner=root group=root mode=0644

  - name: copy the rbdmap file
    copy: src=/etc/ceph/rbdmap dest=/etc/ceph/rbdmap owner=root group=root mode=0644

  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install ceph
    become: true
    apt:
       name: ceph-common 
    apt:
       name: ceph-fuse
    apt:
       name: autofs

  - name: copy the ceph.client.admin file
    copy: src=/home/ubuntu/ceph/ceph.client.admin.keyring dest=/etc/ceph/ceph.client.admin.keyring owner=root group=root mode=0600
    become: yes

  - name: mount the ceph share
    command: mount -a
