---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
          settings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings')}}"

  tasks:
    - name: install swig
    apt:
        name: swig
        state: present
        update_cache: true
    become: yes

    - name: install python-dev
      apt:
#          name: python-dev
          name: libpython3.7-dev
          state: present
          update_cache: true
      become: yes

    - name: install pip3
      apt:
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: install gkhtm
      pip:
          executable: pip3
          name: gkhtm

    - name: install docopt
      pip:
          executable: pip3
          name: docopt

    - name: install numpy
      pip:
          executable: pip3
          name: numpy

    - name: install MOC
      pip:
          executable: pip3
          name: mocpy

    - name: install requests
      pip:
          executable: pip3
          name: requests

    - name: install mysql.connector
      pip:
          executable: pip3
          name: mysql-connector-python

    - name: Make sure the repo is up to date
      git: 
          repo: https://github.com/lsst-uk/lasair-lsst.git
          dest: /home/ubuntu/lasair-lsst

    - name: settings.py TNS
      template:
        src:  /home/ubuntu/lasair-lsst/services/TNS/settings.py.j2
        dest: /home/ubuntu/lasair-lsst/services/TNS/settings.py

    - name: settings.py areas
      template:
        src:  /home/ubuntu/lasair-lsst/services/areas/settings.py.j2
        dest: /home/ubuntu/lasair-lsst/services/areas/settings.py

    - name: settings.py watchlists
      template:
        src:  /home/ubuntu/lasair-lsst/services/watchlists/settings.py.j2
        dest: /home/ubuntu/lasair-lsst/services/watchlists/settings.py
