---
- hosts: sherlocks
  gather_facts: true
  become: true

  vars:
    brokers: "host:9092,host:9092"
    group_id: "sherlock_wrapper_0"
    input_topic: "ztf_ingest"
    output_topic: "ztf_sherlock"
    cache_db: "mysql://user:pass@127.0.0.1/cache"
    sherlock_db: "crossmatch_catalogues"
    sherlock_db_host: "host"
    sherlock_user: "username"
    sherlock_password: "password"

  tasks:
    - name: "Create /opt/lasair directory"
      file:
        path: /opt/lasair
        state: directory

    - name: "Deploy Sherlock config"
      template:
        src:  sherlock_settings.yaml.j2
        dest: /opt/lasair/sherlock_settings.yaml

    - name: "Deploy Sherlock wrapper config"
      template:
        src:  sherlock_wrapper_config.yaml.j2
        dest: /opt/lasair/config.yaml

    - name: "Deploy Docker compose file"
      template:
        src:  sherlock-wrapper-compose.yml.j2
        dest: sherlock-wrapper-compose.yml

    - name: "Start Sherlock wrapper service"
      docker_service:
        project_name: sherlock_wrapper
        project_src:
            '.'
        files:
          - 'sherlock-wrapper-compose.yml'
        services:
          - 'sherlock_wrapper'
        state:
          present

