---
- hosts: sherlocks
  gather_facts: true
  become: true

  vars:
    image: "gpfrancis/sherlock-wrapper:0.5.15"
    brokers: "192.41.108.36:9092,192.41.108.24:9092,192.41.108.36:9092"
    group_id: "sherlock_wrapper_1"
    input_topic: "ztf_ingest"
    output_topic: "ztf_sherlock"
    vault: "{{ lookup('hashi_vault', 'secret=secret/lasair/sherlock')}}"
    cache_db: "mysql://user:pass@127.0.0.1/cache"
    sherlock_db: "crossmatch_catalogues"
    sherlock_db_host: "192.168.0.43"
    sherlock_user: "{{ vault.user }}"
    sherlock_password: "{{ vault.password }}"
    slack_url: "{{ vault.slack_url }}"

  tasks:
    - name: "Create /opt/lasair directory"
      file:
        path: /opt/lasair
        state: directory

    - name: "Deploy Sherlock config"
      template:
        src:  sherlock_settings.yaml.j2
        dest: /opt/lasair/sherlock_settings.yaml

    - name: "Deploy Sherlock wrapper config"
      template:
        src:  sherlock_wrapper_config.yaml.j2
        dest: /opt/lasair/config.yaml

    - name: "Deploy Sherlock wrapper runner config"
      template:
        src:  sherlock_wrapper_runner.json.j2
        dest: /opt/lasair/wrapper_runner.json

    - name: "Deploy Docker compose file"
      template:
        src:  sherlock-wrapper-compose.yml.j2
        dest: sherlock-wrapper-compose.yml

    - name: "Start Sherlock wrapper service"
      docker_service:
        project_name: sherlock_wrapper
        project_src:
            '.'
        files:
          - 'sherlock-wrapper-compose.yml'
        services:
          - 'sherlock_wrapper'
        state:
          present
        scale:
          sherlock_wrapper: 3

