---
- hosts: sherlocks
  gather_facts: true
  become: true

  vars:
    brokers: "192.168.0.25:29092,192.168.0.5:29092"
    group_id: "dev-sherlock-2"
    input_topic: "ztf_test_ingested"
    output_topic: "dev_sherlock_test_output"

  tasks:
    - name: "Create /opt/lasair directory"
      file:
        path: /opt/lasair
        state: directory

    - name: "Deploy Sherlock config"
      template:
        src:  sherlock_settings.yaml.j2
        dest: /opt/lasair/sherlock_settings.yaml

    - name: "Deploy Sherlock wrapper config"
      template:
        src:  sherlock_wrapper_config.yaml.j2
        dest: /opt/lasair/config.yaml

    - name: "Deploy Docker compose file"
      template:
        src:  sherlock-wrapper-compose.yml.j2
        dest: sherlock-wrapper-compose.yml

    - name: "Start Sherlock wrapper service"
      docker_service:
        project_name: sherlock_wrapper
        project_src:
            '.'
        files:
          - 'sherlock-wrapper-compose.yml'
        services:
          - 'sherlock_wrapper'
        state:
          present

