--- # Configuration for sherlock wrapper

# Setting any option on the command line overrides the value in this file

#####################################################################
# REQUIRED SETTINGS
#####################################################################

# comma separated list of Kafka brokers and ports
broker: 192.41.108.22:9092

# topic to consume input messages
input_topic: dev_sherlock_test_input

# topic to produce output messages
output_topic: dev_sherlock_test_output


#####################################################################
# OPTIONAL SETTINGS
#####################################################################

# Kafka client group id
##group: dev-sherlock-1

# Kafka consumer timeout in s
##timeout: 10

# number of messages to process per batch
##batch_size: 1000

##max_messages: 1

# log only critical and error messages
##quiet: false

# log info messages and above
##verbose: false

# log debug messages and above
##debug: false
